---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hasher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: hasher
  targetNamespace: fluxhelmcoins-2
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: webui
  targetNamespace: fluxhelmcoins-2
  values:
    service:
      type: NodePort
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rng
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: rng
  targetNamespace: fluxhelmcoins-2
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: redis
  targetNamespace: fluxhelmcoins-2
  values:
    image:
      repository: redis
      tag: latest
    livenessProbe:
      exec:
        command:
        - "true"
    service:
      port: 6379
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: worker
  targetNamespace: fluxhelmcoins-2
  values:
    readinessProbe:
      exec:
        command:
        - "true"
    service: false
