---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxhelmcoins-1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/helmcoins-1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: fluxhelmcoins-1
  targetNamespace: fluxhelmcoins-1
